### ISSUE TITLE
Add A Series of New Fine-Tuned Judge Models

### ISSUE THREAD

**Issue by bittersweet1999** [ScalerLab/JudgeBench#2]
Hi JudgeBench Team 👋,

We have updated a series of Fine-Tuned Judge Models:
[opencompass/CompassJudger-1-32B-Instruct](https://huggingface.co/opencompass/CompassJudger-1-32B-Instruct)
[opencompass/CompassJudger-1-14B-Instruct](https://huggingface.co/opencompass/CompassJudger-1-14B-Instruct)
[opencompass/CompassJudger-1-7B-Instruct](https://huggingface.co/opencompass/CompassJudger-1-7B-Instruct)
[opencompass/CompassJudger-1-1.5B-Instruct](https://huggingface.co/opencompass/CompassJudger-1-1.5B-Instruct)

Our local evaluation metrics for the model are listed below, where CJ-1-32B achieved the best performance among the currently open-source General Judge Models
For **CompassJudger-1-32B-Instruct**: 57.71
![图片](https://github.com/user-attachments/assets/aa5d5458-ce54-43f9-b6bb-d6655735251a)
For **CompassJudger-1-14B-Instruct**: 56.28
![图片](https://github.com/user-attachments/assets/839a3b2b-661f-4fb3-8e54-e18ff4550de2)
For **CompassJudger-1-7B-Instruct**: 48
![图片](https://github.com/user-attachments/assets/265a7bb9-052d-478c-a374-5c3e26d25f28)
For **CompassJudger-1-1.5B-Instruct**: 42
![图片](https://github.com/user-attachments/assets/214530f1-8433-451d-9dfa-2aae42be6763)

We would like to add these series of new generative models to the JudgeBench LeaderBoard.

Thank you!

Besides, your work **JudgeBench** bears some similarity to our **JudgerBench**. We welcome you to also refer to our work (https://github.com/open-compass/CompassJudger) to jointly advance the iteration of Judge/Reward models.

**Comment by kylemontgomery1** [comment]
Hmm... I'm not able to replicate these results exactly. Could you review the implementation [here](/ScalerLab/JudgeBench/tree/compassjudger) and update it if needed?

Here are the result I got:
```
CompassJudger-1-1.5B-Instruct:
mmlu_pro: 40.26%
livebench-reasoning: 37.76%
livebench-math: 46.43%
livecodebench: 26.19%
overall: 38.86%

CompassJudger-1-7B-Instruct:
mmlu_pro: 38.96%
livebench-reasoning: 40.82%
livebench-math: 62.50%
livecodebench: 33.33%
overall: 42.57%

CompassJudger-1-14B-Instruct:
mmlu_pro: 44.81%
livebench-reasoning: 48.98%
livebench-math: 62.50%
livecodebench: 42.86%
overall: 48.57%

CompassJudger-1-32B-Instruct:
mmlu_pro: 55.19%
livebench-reasoning: 53.06%
livebench-math: 67.86%
livecodebench: 45.24%
overall: 55.43%
```

Keep in mind that slight variations in scores is expected due to non-deterministic CUDA ops and rounding errors. For example, across 5 runs with CompassJudger-1-1.5B-Instruct, I observed the following overall scores: [38.86%, 37.43%, 39.14%, 38.57%, 38.29%]. However, given the significance of the difference between your reported results and the results I obtained, I expect that it's due some differences between our respective implementations.

**Comment by bittersweet1999** [comment]
Hi, thanks for your testing~
And I changed to your code with `compassjudger` branch, 
I run the code as below:
Firstly, launch a vllm server for compassjudger-1.5b:
`python -m vllm.entrypoints.openai.api_server --model opencompass/CompassJudger-1-1.5B-Instruct`
Then, run:
`python run_judge.py --judge_name compass_judger --judge_model opencompass/CompassJudger-1-1.5B-Instruct --pairs data/dataset=judgebench,response_model=gpt-4o-2024-05-13.jsonl`
and I got below results:
![图片](https://github.com/user-attachments/assets/e7843f63-ec55-4814-b476-3346a88b7a46)

**Comment by bittersweet1999** [comment]
> Hi, thanks for your testing~ And I changed to your code with `compassjudger` branch, I run the code as below: Firstly, launch a vllm server for compassjudger-1.5b: `python -m vllm.entrypoints.openai.api_server --model opencompass/CompassJudger-1-1.5B-Instruct` Then, run: `python run_judge.py --judge_name compass_judger --judge_model opencompass/CompassJudger-1-1.5B-Instruct --pairs data/dataset=judgebench,response_model=gpt-4o-2024-05-13.jsonl` and I got below results: ![图片](https://private-user-images.githubusercontent.com/148421775/383420922-e7843f63-ec55-4814-b476-3346a88b7a46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NzIzOTUsIm5iZiI6MTczMDg3MjA5NSwicGF0aCI6Ii8xNDg0MjE3NzUvMzgzNDIwOTIyLWU3ODQzZjYzLWVjNTUtNDgxNC1iNDc2LTMzNDZhODhiN2E0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQwNTQ4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWViMDQyMDg5MWJkNWY1MWFkNWFmYjcxOWUyMmE1ODAwNDMxOGI5YjJhMGI0N2JlMGQxZjZiN2NmNzJlOWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Bqqg_AkSx_AdjMaT0aSSwHnwlxdsZVD3gRdPAzAKz28)
[dataset=judgebench,response_model=gpt-4o-2024-05-13,judge_name=compass_judger,judge_model=opencompass_CompassJudger-1-1.5B-Instruct.json](https://github.com/user-attachments/files/17642304/dataset.judgebench.response_model.gpt-4o-2024-05-13.judge_name.compass_judger.judge_model.opencompass_CompassJudger-1-1.5B-Instruct.json)

And this is the json file (can not upload jsonl file) for the above results

**Comment by bittersweet1999** [comment]
BTW, In my original test, since the compassjudger does not need a special prompt template, so I actually used the original arenahard judge template as `python run_judge.py --judge_name arena_hard --judge_model opencompass/CompassJudger-1-1.5B-Instruct --pairs data/dataset=judgebench,response_model=gpt-4o-2024-05-13.jsonl`,
And I tried again with your code to test arenahard template, it also got the results as below:
![图片](https://github.com/user-attachments/assets/7f651790-2f04-4198-9175-94e414d3374c)

So it seems no difference for the two prompt templates when testing compassjudger.

[dataset=judgebench,response_model=gpt-4o-2024-05-13,judge_name=compass_judger,judge_model=opencompass_CompassJudger-1-1.5B-Instruct.json](https://github.com/user-attachments/files/17642893/dataset.judgebench.response_model.gpt-4o-2024-05-13.judge_name.compass_judger.judge_model.opencompass_CompassJudger-1-1.5B-Instruct.json)

**Comment by kylemontgomery1** [comment]
Interesting, what does seem to matter is whether or not the system prompt is separated from the user prompt. E.g., 

```python
messages = [
    {"role": "system", "content": system_message + "\n" + user_message}
]

messages = [
    {"role": "system", "content": system_message},
    {"role": "user", "content": user_message},
]
```

I've updated the implementation [here](/ScalerLab/JudgeBench/tree/compassjudger) to use the latter. With this implementation, I observed the follow results, which are much closer to (often surpassing) what you had originally observed:

```
CompassJudger-1-1.5B-Instruct:
mmlu_pro: 48.05%
livebench-reasoning: 39.80%
livebench-math: 50.00%
livecodebench: 35.71%
overall: 44.57%

CompassJudger-1-7B-Instruct:
mmlu_pro: 42.21%
livebench-reasoning: 37.76%
livebench-math: 69.64%
livecodebench: 47.62%
overall: 46.00%

CompassJudger-1-14B-Instruct:
mmlu_pro: 51.95%
livebench-reasoning: 60.20%
livebench-math: 67.86%
livecodebench: 42.86%
overall: 55.71%

CompassJudger-1-32B-Instruct:
mmlu_pro: 58.44%
livebench-reasoning: 62.24%
livebench-math: 75.00%
livecodebench: 59.52%
overall: 62.29%
```

Please let me know if these results look okay. If so, I'll merge the implementation into main and add these results to our leaderboard on huggingface.

**Comment by bittersweet1999** [comment]
Well, thanks again for your testing, these results seems well!
And ene possible explanation is that during the training of CompassJudger, we adopted separating system prompts from user prompts, which might make it more suitable for its judging.

**Comment by kylemontgomery1** [comment]
Just updated [our Leaderboard](https://huggingface.co/spaces/ScalerLab/JudgeBench). Thanks for your help!
