### ISSUE TITLE
Question about LLM judgements data

### ISSUE THREAD

**Issue by felipemaiapolo** [ScalerLab/JudgeBench#5]
Dear authors,

Congrats on the cool paper! I wanted to ask you if it's possible for you to share the LLM judgment data as well. I would use your data for my research and wanted to avoid running judges again if possible. 

Thank you!
Felipe

**Comment by kylemontgomery1** [comment]
Hi! I think you will find what you're looking for under `outputs/`. Each file corresponds to a specific judge and contains the pairwise judgments for each question in JudgeBench. Hopefully this helps!
